### ISSUE TITLE
Custom Command and responseClass

### ISSUE THREAD

**Issue by L0rD59** [guzzle/guzzle3#43]
Hi,

I've some trouble for return custom model from custom command

i've tried a description like this : 

```
"getProspectByPhone" => array(
            "class" => "LIG\\PRM\\API\\Command\\GetProspectByPhone",
            "responseClass" => "LIG\\PRM\\API\\Model\\Prospect", // Prospect
            "summary" => "Get a prospect by phone",
        ),
```

but didn't works,

I saw that I had to create my custom process function and custom parser, but i cannot do :( 

do you have some example ?

Thx a lot for your time

[Edit]
The `ResponseClassInterface::fromCommand` require a `OperationCommand` parameter, not a CustomCommand `CommandInterface`

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now. Please upgrade to Guzzle 7 ASAP.
