### ISSUE TITLE
URL-Encoding of the path

### ISSUE THREAD

**Issue by xelaris** [guzzle/guzzle3#51]
I use Guzzle to load files from a server. It occures that file names include unsafe characters. E.g. there are files with something like german umlauts like "Ru\xCC\x88ckansicht" (already urlencoded here) instead of "Rückansicht".  It's an 'u' followed by a diaeresis (unicode U+0308), not an umlaut. It is not possible to fetch such a file with Guzzle when passing the original utf8 file name. Browsers like Chrome and Firefox seems to encode the character when entering or copy-pasting the diaeresis character in an URL, so the request paths looks like "/xu%CC%88x.txt" and such a file can be loaded. Guzzle don't do such an encoding. I don't know the "right" way to do it or how the browsers do it, but the following example solves the issue:

``` php
$client = new \Guzzle\Http\Client();

$path = 'testfiles/xüx.txt';

$path = implode(
  '/',
  array_map(
    function ($part) {
      return rawurlencode($part);
    },
    explode('/', $path)
  )
);

//$path = 'testfiles/xu%CC%88x.txt';

$request = $client->get('http://dev.xelaris.net/' . $path);
$response = $request->send();
```

I wonder if this encoding should be done by Guzzle, like browsers do, so the filepath can be passed to Guzzle without doing this encoding before. I experienced this issue with Guzzle 3 but it seems to be the same for Guzzle 5. The URL http://dev.xelaris.net/testfiles/xüx.txt can be used for testing. The devtools shows the request path is "/testfiles/xu%CC%88x.txt" instead of  "/testfiles/x%C3%BCx.txt" since it is not the german umlaut ü.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now. Please upgrade to Guzzle 7 ASAP.
