### ISSUE TITLE
Please "abandon" your package on packagist

### ISSUE THREAD

**Issue by c33s** [guzzle/guzzle3#59]
even if you support it until late 2015 you should mark your package as abandoned, so people don't start using the wrong version.

see https://github.com/composer/packagist/pull/421
live example: https://packagist.org/packages/zenstruck/slugify-bundle

**Comment by GrahamCampbell** [comment]
It's not abandoned yet though. :-1:

It should only be marked as abandoned they day you stop fixing bugs all together, and not before.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Well, this issue can be still opened unless guzzle3 will be not maintained anymore. :+1:

**Comment by csarrazi** [comment]
As this version of the library is EOL, it should be marked as abandoned, so people may see an informational message when running `composer install` or `composer update`, and start upgrading their clients to Guzzle 5 or 6.

**Comment by LawnGnome** [comment]
It seems like this has happened, per:

```
$ composer require guzzle/guzzle ^3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/event-dispatcher (v2.8.27)
    Loading from cache

  - Installing guzzlehttp/guzzle (v3.8.1)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.9.3)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

I think this could be closed.
