### ISSUE TITLE
Support Symfony 3

### ISSUE THREAD

**Issue by dosten** [guzzle/guzzle3#68]
Hi there!

I'm upgrading an application to Symfony 3 but I can't because a dependency (https://github.com/intercom/intercom-php) relies on Guzzle 3, this happens because Guzzle relies on `symfony/event-dispatcher:~2.1` (see https://github.com/guzzle/guzzle3/blob/master/composer.json#L49).
Maybe we can update the dep to `~2.1|~3.0`, yes, I know that Guzzle 3 is EOL, but maybe you can consider it.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Upgrade to guzzle 6.
