### ISSUE TITLE
security issue present in many clis

### ISSUE THREAD

**Issue by cordoval** [guzzle/guzzle3#71]
There is a concern that was raised about copying the .pem in /tmp folder world writable

https://github.com/gushphp/gush/issues/531

This has to do with the cert.pem copied that many https://github.com/search?q=guzzle-cacert.pem&type=Code&utf8=%E2%9C%93 repos do. Is there a work around for this?

**Comment by glensc** [comment]
php should be able to read cert from phar file using stream wrappers, why does it need to be copied outside phar? besides, most linux distros ship their own system ca-certificates which is kept up to date os update mechanisms

  - https://packages.debian.org/sid/ca-certificates
  - https://github.com/openSUSE/ca-certificates
  - https://launchpad.net/ubuntu/+source/ca-certificates
  - https://fedoraproject.org/wiki/CA-Certificates

**Comment by pierredup** [comment]
Guzzle 3 is deprecated and not maintained anymore, so I don't think this issue will get any attention.
And with the latest version of Guzzle, the system certificates are used, have a look at https://github.com/guzzle/guzzle/blob/5c12b74e9405c50fb0fd6ab831dd6e9df5560b1f/src/functions.php#L161
