### ISSUE TITLE
compatibility symfony 3.0

### ISSUE THREAD

**Issue by pinouf** [guzzle/guzzle3#72]
Hello, 

Could you please create a tag compatible with symfony 3.0.

Thanks, =)

**Comment by GrahamCampbell** [comment]
Not going to happen. Guzzle 3 is EOL.

**Comment by pinouf** [comment]
What is EOL ?

**Comment by GrahamCampbell** [comment]
End of life. Dead. Not maintained. No more releases.

**Comment by pinouf** [comment]
ohhh, i didn't see that the bundle was deprecated.
my bad =)
thanks for the information.
