### ISSUE TITLE
Uncaught exception - with message 'Errors during multi transfer

### ISSUE THREAD

**Issue by arpan03** [guzzle/guzzle3#73]
Hi,

I am trying to send a large chunk of commands using batchbuilder. 

When I run my script it runs fine for sometime then it throws this error:

```
PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException' with message 'Errors during multi transfer
(Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

[curl] 77: error setting certificate verify locations:
  CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
  CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

#0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php on line 62
```

Before using batchbuilder I was getting this error:

```
PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException'     with message 'Errors during multi transfer
(Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

[curl] 77: error setting certificate verify locations:
  CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
  CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

#0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Service/Exception/CommandTransferException.php on line 25
```

I thought using batchbuilder will fix this problem but that was not to be. 

Here is how i'm implementing my logic:

```
use Aws\Ses\SesClient;
use Guzzle\Batch\BatchBuilder;
use Guzzle\Service\Exception\CommandTransferException;

//Create array of commands
$this->commands = array();

//Logic to fill this array with commands
$msg = array();

$msg['Source'] = "$header <noreply@domain.com>";
$msg['Destination']['ToAddresses'][] = "test@gmail.com";
$msg['Message']['Subject']['Data'] = "Testing guzzle batching";
$msg['Message']['Subject']['Charset'] = "UTF-8";
$msg['Message']['Body']['Text']['Data'] ="";
$msg['Message']['Body']['Text']['Charset'] = "UTF-8";
$msg['Message']['Body']['Html']['Data'] ="test data";
$msg['Message']['Body']['Html']['Charset'] = "UTF-8";

$client = SesClient::factory(array(
        'key'    => '<KEY>',
        'secret' => '<SECRET>',
        'region' => 'us-east-1'
    ));
$this->commands[]= $client->getCommand('SendEmail',$msg);

//Create batchbuilder
$batch = BatchBuilder::factory()->transferCommands(10)->build();
        foreach ($this->commands as $command) {
            $batch->add($command);
        }
        $batch->flush();
```

**Comment by arpan03** [comment]
Getting same error after trying automatically flushing a queue autoFlushAt(10)

    $batch = BatchBuilder::factory()
			    ->transferCommands(10)
			    ->autoFlushAt(10)
			    ->build();

Error: 

    PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException' with message 'Errors during multi transfer
    (Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

    [curl] 77: error setting certificate verify locations:
      CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
      CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

    #0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php on line 62

**Comment by kesavankrishnan** [comment]
Getting the same error while uploading file into S3 via AWS SDK
CommandTransferException Error ==> Errors during multi transfer\n(Guzzle\\Http\\Exception\\CurlException

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now. Please upgrade to Guzzle 7 ASAP.
