### ISSUE TITLE
xml() method - docs outdated?

### ISSUE THREAD

**Issue by toby1kenobi** [guzzle/guzzle3#79]
Trying to use xml() on a Guzzle (current version) response results in an exception:

Call to undefined method GuzzleHttp\Psr7\Response::xml()

and indeed there doesn't seem to be an xml method for that class.

**Comment by GrahamCampbell** [comment]
This is the guzzle 3 repo. Your code is guzzle 6.

**Comment by toby1kenobi** [comment]
Apologies, will look/try again
