### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by slavafomin** [guzzle/guzzle3#81]
Hello!

Thank you for this great library!

However, the documentation link in the README is broken:
http://guzzle3.readthedocs.io/en/latest/

Where do I find docs for this version of Guzzle?

Thanks!

**Comment by slavafomin** [comment]
I've tried to build it myself using `make html`, but I'm getting the error: `unsupported theme option 'github_user' given`.

**Comment by slavafomin** [comment]
Just found the docs here:
http://guzzle3.readthedocs.io/http-client/client.html#request-options

I hope they are up to date to the version of this repo. Please fix the link in the README please.

Thanks!

**Comment by mtdowling** [comment]
I've updated the readme to remove the docs link.

https://github.com/guzzle/guzzle3/commit/f7778ed85e3db90009d79725afd6c3a82dab32fe
