### ISSUE TITLE
Guzzle JSON request with ascii encrypted(sensitive) data

### ISSUE THREAD

**Issue by ijerry** [guzzle/guzzle3#83]
Hi 
I am getting a 401 for a request that contains a JSON blob with one field containing  an encrypted-payload of type ascii data. My suspicion is that i am not handling the this string(encrypted-payload) correctly. From the time i read it in in BDD behat pystring format to the time i send it to the server.

If i shorten the above payload encrypted-payload  to 2 characters. (to confirm my suspicion that there are some characters in the string that i am not dealing with correctly)

i get a 400 (bad device serial) error.  Which means i am getting through authentication and request is being processed but actual apppliation specific request is bad  -  bad device serial.

In essence i am getting further.

Below is code on how i convert my ascii (encrypted-payload) to array format and call the guzzle post request.

            $requestBodyArrayFormat = json_decode($request->_uri[0]);
            $obj->_response = $request->_client->request('POST', $request->_url, [
                'headers' => ['Content-Type' => 'application/json; charset=UTF-8',
                    'Authorization' => $hmacHeader
                ],
                'debug' => true, // turn on debug
                'json' => $requestBodyArrayFormat, 
                'handler' => $tapMiddleware($clientHandler)
            ]);
 
Any help much appreciated.

**Comment by ijerry** [comment]
Is there a way to ssl connections in php storm to see the raw frame what is being sent.

Something like this command in Java.
System.setProperty("javax.net.debug","ssl:plaintext");

**Comment by ijerry** [comment]
How ever when i use php curl_exec, it works.

            $data_string = rawJsonData;;
         
            $ch = curl_init('https://url/api/v1/service1/pat/');
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                    'Content-Type: application/json',
                    'Authorization: ' . $hmacHeader)
            );

**Comment by Konafets** [comment]
Which version of Guzzle do you use? This is the repository for version 3 which is deprecated. In case you don't using the latest version, upgrade and check if the error is still valid and if so, open an issue at https://github.com/guzzle/guzzle/issues

**Comment by ijerry** [comment]
Moving to latest guzzle version channel.
https://github.com/guzzle/guzzle/issues/1849
