### ISSUE TITLE
SSL certificate unable to get local issuer

### ISSUE THREAD

**Issue by thomaslorentsen** [guzzle/guzzle3#89]
I am getting an SSL certificate exception thrown when using this library:
```
Guzzle\\Http\\Exception\\CurlException: [curl] 60: SSL certificate problem: unable to get local issuer certificate 
```
I am currently having to fix it by manually upgrading the certificate in place like this:
```bash
curl -s -o vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem \
    https://curl.haxx.se/ca/cacert.pem
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now. Please upgrade to Guzzle 7 ASAP.
